### DISCUSSION TITLE
paperless-gpt LLM-OCR never runs - failing with connection errors

### DISCUSSION THREAD

**Discussion by ashkenazzio** [icereed/paperless-gpt#375] [Q&A]
I am trying to LLM-OCR my receipts since I'm getting poor native performance. I can't get it to work properly even though my setup seems to be legit and healthy:

## Environment

- **Host OS:** Arch Linux  

---

## Docker Compose

```yaml
services:
  broker:
    image: redis:7-alpine
    user: "1100:1100"
    restart: always
    volumes:
      - ./data/redisdata:/data

  db:
    image: postgres:16-alpine
    user: "1100:1100"
    restart: always
    environment:
      POSTGRES_DB: ${PAPERLESS_DBNAME}
      POSTGRES_USER: ${PAPERLESS_DBUSER}
      POSTGRES_PASSWORD: ${PAPERLESS_DBPASS}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  paperless-ngx:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1100:1100"
    restart: always
    depends_on:
      - broker
      - db
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      # Core DB & timezone
      PAPERLESS_DBHOST: ${PAPERLESS_DBHOST}
      PAPERLESS_DBNAME: ${PAPERLESS_DBNAME}
      PAPERLESS_DBUSER: ${PAPERLESS_DBUSER}
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS}
      PAPERLESS_TIME_ZONE: Asia/Jerusalem

      # OCRmyPDF preprocessing
      PAPERLESS_OCR_CLEAN: clean-final
      PAPERLESS_OCR_DESKEW: "true"
      PAPERLESS_OCR_ROTATE_PAGES: "true"
      PAPERLESS_OCR_ROTATE_THRESHOLD: "30"

      # Languages & whitelist
      PAPERLESS_OCR_LANGUAGE: "heb+eng"
      PAPERLESS_OCR_USER_ARGS: >-
        {"tesseract_oem":1,"tesseract_pagesegmode":6,
         "tesseract_config":["tessedit_char_whitelist=אבגדהוזחטיכלמנסעפצקרשת־ 0123456789"]}

      # RTL post-processing
      PAPERLESS_CONSUMER_POST_PROCESSING: /usr/local/bin/bidi_reorder.sh

      # Redis connection (was trying localhost before)
      PAPERLESS_REDIS: redis://broker:6379/0

      # Admin & API
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
      PAPERLESS_API_TOKEN: ${PAPERLESS_API_TOKEN}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS}
      PAPERLESS_PUBLIC_URL: ${PAPERLESS_PUBLIC_URL}

    volumes:
      - ./data/appdata:/usr/src/paperless/data
      - ./data/media:/usr/src/paperless/media
      - ./data/consume:/usr/src/paperless/consume
      - ./data/export:/usr/src/paperless/export
      - ./scripts:/opt/paperless/scripts:ro

  paperless-gpt:
    image: icereed/paperless-gpt:latest
    user: "1100:1100"
    restart: always
    depends_on:
      - paperless-ngx
    env_file: .env
    environment:
      # Connect to Paperless-ngx
      PAPERLESS_BASE_URL:   http://paperless-ngx:8000
      PAPERLESS_URL:      http://paperless-ngx:8000
      PAPERLESS_API_TOKEN: ${PAPERLESS_API_TOKEN}
      PAPERLESS_TOKEN: ${PAPERLESS_API_TOKEN}
      # if you ever enable HTTPS in Paperless, skip cert checks:
      PAPERLESS_INSECURE_SKIP_VERIFY: "true"
      PAPERLESS_PUBLIC_URL: ${PAPERLESS_PUBLIC_URL}
      OCR_AUTO:                     "true"

      # LLM/OCR settings
      LLM_PROVIDER: ollama
      LLM_MODEL: deepseek-r1:8b
      OCR_PROVIDER: llm
      VISION_LLM_PROVIDER: ollama
      VISION_LLM_MODEL: deepseek-r1:8b
      OLLAMA_HOST: http://host.docker.internal:11434

      # Tagging & logging
      MANUAL_TAG: paperless-gpt
      AUTO_TAG: paperless-gpt-auto
      LOG_LEVEL: info

    volumes:
      - ./data/prompts:/app/prompts
      - ./data/paperless-gpt-db:/app/db
```

## `.env`
```
# Database (for both Paperless-ngx & your Postgres service)
PAPERLESS_DBHOST=db
PAPERLESS_DBNAME=paperless
PAPERLESS_DBUSER=paperless
PAPERLESS_DBPASS=paperless

# Admin credentials for Paperless-ngx UI
PAPERLESS_ADMIN_USER=admin
PAPERLESS_ADMIN_PASSWORD=paperless

# API & security
PAPERLESS_API_TOKEN=fc07efd64982c6784dc74bd2c728c2578d540eb0
PAPERLESS_SECRET_KEY=wD8fiRBin4tSSaN9Q0-CJh_GLd7UrlDEfmtOiklrNGBnd1t3qcBW0nJhpIk_sMbj6MY

# Host & URL settings
PAPERLESS_ALLOWED_HOSTS=localhost,paperless-ngx
PAPERLESS_PUBLIC_URL=http://localhost:8000
```

## Observed Behavior
1. Startup logs show only the banner and “Worker 0 started.”

2. Immediately thereafter, repeated errors:
`HTTP request failed: Get "http://paperless-ngx:8000/api/documents/?tags__name__iexact=paperless-gpt-ocr-auto…": dial tcp …: connect: connection refused`

3. Even once Paperless-ngx is healthy (responding to `curl http://localhost:8000/api/documents/`), no auto-OCR loop ever succeeds.

4. I tagged a document with paperless-gpt in the UI, restarted the GPT container, but still no LLM execution.

## Questions

1. Why does the worker keep failing to connect, even when the API is healthy?

2. What’s the intended lifecycle for the manual-tag OCR path—should it pick up tags added after startup, and if so how?

Any pointers to get the LLM-OCR worker to actually process documents would be greatly appreciated. Thanks!
