### DISCUSSION TITLE
"Mistral Magic" - Smarter OCR, Sharper PDFs 🌟

### DISCUSSION THREAD

**Discussion by icereed** [icereed/paperless-gpt#378] [Announcements]
### 🤖 Mistral AI Integration
- Added Mistral AI as a new provider for both OCR and LLM capabilities
- Integrated Vision models for adaptable document processing
- Added dedicated OCR service optimized for document processing
- Included configuration options for OCR methods
- Enhanced rate limiting with retry mechanisms for stable API interaction

### 📄 PDF Processing Improvements
- Implemented intelligent PDF page extraction with size optimization
- Added smart dimension limits (10K pixels max per side, 40MP total)
- Introduced adaptive JPEG quality adjustment (85-60 range)
- Added intelligent resizing based on target file size
- Fixed issues with oversized PDF page extractions

### ⚡ Performance
- Implemented rate limiting and retry controls for LLM requests
- Added configurable rate limits via environment variables
- Optimized image processing for better resource utilization

### 🧪 Testing & Documentation
- Added comprehensive tests for Mistral OCR provider
- Added tests for rate-limited LLM client behavior
- Expanded test coverage for image processing and error scenarios
- Added documentation for Mistral integration and configuration

## PRs
* fix: oversized PDF page extractions by @gardar in https://github.com/icereed/paperless-gpt/pull/362
* fix(deps): update module github.com/gabriel-vasile/mimetype to v1.4.9 by @renovate in https://github.com/icereed/paperless-gpt/pull/351
* chore(deps): update dependency dotenv to v16.5.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/343
* fix(deps): update dependency @headlessui/react to v2.2.2 by @renovate in https://github.com/icereed/paperless-gpt/pull/350
* chore(deps): update dependency @types/node to v22.15.3 by @renovate in https://github.com/icereed/paperless-gpt/pull/342
* fix(deps): update github.com/gardar/ocrchestra digest to 2d28866 by @renovate in https://github.com/icereed/paperless-gpt/pull/364
* chore(deps): update dependency testcontainers to v10.25.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/369
* chore(deps): update dependency @playwright/test to v1.52.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/367
* chore(deps): update dependency @vitejs/plugin-react-swc to v3.9.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/368
* fix(deps): update dependency axios to v1.9.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/372
* Adds Mistral AI integration for OCR and LLM by @icereed in https://github.com/icereed/paperless-gpt/pull/366
* chore(deps): update dependency vite to v6.3.4 by @renovate in https://github.com/icereed/paperless-gpt/pull/371
* fix(deps): update module google.golang.org/api to v0.231.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/374
* fix(deps): update dependency react-router-dom to v7.5.3 by @renovate in https://github.com/icereed/paperless-gpt/pull/334
* fix(deps): update dependency react-tooltip to v5.28.1 by @renovate in https://github.com/icereed/paperless-gpt/pull/338

**Full Changelog**: https://github.com/icereed/paperless-gpt/compare/v0.16.0...v0.17.0

<hr /><em>This discussion was created from the release <a href='https://github.com/icereed/paperless-gpt/releases/tag/v0.17.0'>"Mistral Magic" - Smarter OCR, Sharper PDFs 🌟</a>.</em>

**Comment by klim123123** [comment]
Thank you for adding Mistral!
For some reason some of my document partially not recognized, and i see  `![img-0.jpeg](img-0.jpeg)` in text.
I found some information on [reddit](https://www.reddit.com/r/MistralAI/comments/1jbvm3g/mistral_ocr_refuses_to_ocr/)

I tested with chatgpt, everything is recognized.
I tested with Mistral Le Chat, everything is recognized.

Any suggestions please.

**Reply by icereed** [reply]
Hi :)
Can you post your settings? (the non-confidential ones ;) )

**Reply by klim123123** [reply]
```
  paperless-gpt:
    image: ghcr.io/icereed/paperless-gpt:v0.18.0
    container_name: paperless-gpt
    restart: unless-stopped
    depends_on:
      - webserver
    environment:
      PAPERLESS_API_TOKEN: xxx
      PAPERLESS_BASE_URL: "http://webserver:8000"
      MANUAL_TAG: "paperless-gpt" # Optional, default: paperless-gpt
      AUTO_TAG: "paperless-gpt-auto" # Optional, default: paperless-gpt-auto
#      LLM_PROVIDER: "openai"
#      LLM_MODEL: "gpt-4o"
      OPENAI_API_KEY: "xxx"
      # Option 2: Mistral
      LLM_PROVIDER: "mistral"
      LLM_MODEL: "mistral-large-latest"
      LLM_LANGUAGE: "Russian"
      MISTRAL_API_KEY: 'xxxx'
      OCR_PROVIDER: "mistral_ocr"
      # Optional: specify model version
      MISTRAL_MODEL: 'mistral-ocr-latest'
      PDF_OCR_TAGGING: "true" # Optional, add tag to processed documents
      PDF_OCR_COMPLETE_TAG: "ocr-ok" # Optional, tag name
      AUTO_OCR_TAG: "gpt-ocr-auto" # Optional, default: paperless-gpt-ocr-auto
      PDF_UPLOAD: "true"
      PDF_REPLACE: "false"
```
