### DISCUSSION TITLE
"Workflow Greatness" - Automated Document Processing Pipeline 🔄

### DISCUSSION THREAD

**Discussion by icereed** [icereed/paperless-gpt#383] [Announcements]
### New Features 🚀
1. OCR Completion Tags
   - Automatically tag documents after OCR processing is complete using `PDF_OCR_COMPLETE_TAG`
   - Enable workflow automations based on OCR completion status
   - Works seamlessly with all OCR providers

### Quick Setup Guide 🛠️
```yaml
environment:
  # For automatic OCR processing
  AUTO_OCR_TAG: "paperless-gpt-ocr-auto"  # Tag documents to trigger automatic OCR

  # Enable OCR completion tagging
  PDF_OCR_TAGGING: "true"
  PDF_OCR_COMPLETE_TAG: "paperless-gpt-ocr-complete"  # Tag added after OCR completion
```

### How It Works 📋
1. Tag a document with `paperless-gpt-ocr-auto` to queue it for OCR processing
2. Document is processed using your configured OCR provider
3. Upon completion, the document is automatically tagged with `paperless-gpt-ocr-complete`
4. Use these tags to trigger further automations or workflows

### Technical Improvements ⚙️
- Enhanced test coverage for OCR workflow automation
- Improved document processor architecture
- Optimized test execution with parallel workers

## What's Changed
* Fix OCR completion tag and adds OCR document processing E2E test by @icereed in https://github.com/icereed/paperless-gpt/pull/379
* fix(deps): update module gorm.io/gorm to v1.26.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/377
* chore(deps): update dependency vite to v6.3.5 by @renovate in https://github.com/icereed/paperless-gpt/pull/381
* chore(deps): update dependency @types/react-dom to v19.1.3 by @renovate in https://github.com/icereed/paperless-gpt/pull/365
* chore(deps): update dependency typescript-eslint to v8.31.1 by @renovate in https://github.com/icereed/paperless-gpt/pull/337
* fix(deps): update module cloud.google.com/go/documentai to v1.37.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/373
* chore(deps): update eslint monorepo to v9.26.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/332
* chore(deps): update dependency eslint-plugin-react-refresh to v0.4.20 by @renovate in https://github.com/icereed/paperless-gpt/pull/349
* fix(deps): update github.com/gardar/ocrchestra digest to 5fe7a0d by @renovate in https://github.com/icereed/paperless-gpt/pull/376
* fix(deps): update module golang.org/x/sync to v0.14.0 by @renovate in https://github.com/icereed/paperless-gpt/pull/382

**Full Changelog**: https://github.com/icereed/paperless-gpt/compare/v0.17.0...v0.17.1

<hr /><em>This discussion was created from the release <a href='https://github.com/icereed/paperless-gpt/releases/tag/v0.18.0'>"Workflow Greatness" - Automated Document Processing Pipeline 🔄</a>.</em>
