### ISSUE TITLE
Documentation updates - how to use existing Paperless-NGX instance & change ports

### ISSUE THREAD

**Issue by maelstrm-code** [icereed/paperless-gpt#248]
Thought I'd share the results of some extended tinkering in case it helps others or is useful for the documentation.

Note: I'm still getting familiar with docker so let me know if there's a better way and/or if I've done something dumb.

1) If you have an existing paperless-ngx container then comment out the lines in services

```
services:
#  paperless-ngx:
#    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    # ... (your existing paperless-ngx config)
```

2) If the port name is already taken you need to update the ports line with the new port, and also add a LISTEN_INTERFACE line with the interface:port you want it to listen on. You might want to use the interface IP rather than 0.0.0.0 which is everything I believe.

Example

```
 paperless-gpt:
    environment:
      LISTEN_INTERFACE: "0.0.0.0:8810"
    ports:
      - "8810:8810"
```

3) If you are running a custom docker network and want to have your paperless-gpt docker image talk to others eg an external paperless & redis, then add a networks section to the compose file like the one below. I found it worked best to specify it before services, and then you need to add networks line referring to it under port.

Example

```
networks:
  mynetworkname:
    name: mynetworkname
    external: true

services:
#(...)
    ports:
      - "8080:8080"
    networks:
      - mynetworkname
```
