### ISSUE TITLE
Server starts at port 8080 no matter the value in docker compose

### ISSUE THREAD

**Issue by DM2602** [icereed/paperless-gpt#25]
Hi, tried setting up paperless-gpt along my paperless-ngx instance, but can't get it to work and the log tells me it's always starting to listen at port 8080, but that's occupied already.

`Server started on port :8080`

No matter the value I set in my docker compose, the outcome is the same.

**Comment by icereed** [comment]
Hi @DM2602,

can you post your docker-compose.yaml?

**Comment by DM2602** [comment]
```
  paperless-gpt:
    image: icereed/paperless-gpt:latest
    environment:
      PAPERLESS_BASE_URL: 'http://192.168.178.35:8010'
      PAPERLESS_API_TOKEN: 'TOKENHERE'
      GIN_MODE: release
      LLM_PROVIDER: 'openai' # or 'ollama'
      LLM_MODEL: 'gpt-4o'     # or 'llama2'
      OPENAI_API_KEY: 'TOKENHERE' # Required if using OpenAI
      LLM_LANGUAGE: 'German' # Optional, default is 'English'
      OLLAMA_HOST: 'http://host.docker.internal:11434' # If using Ollama
    volumes:
      - ./prompts:/app/prompts # Mount the prompts directory
    ports:
      - '8040:8030'
    depends_on:
      - webserver
```

**Comment by icereed** [comment]
Hi DM2602,

I’m sorry you’re running into issues with setting up **paperless-gpt** alongside your **paperless-ngx** instance. Let’s get this sorted out!

### **Problem Recap**
- **Error:** `paperless-gpt` is trying to listen on **port `8080`**, which is already in use.
- **Current Port Mapping:**
  ```yaml
  ports:
    - '8040:8030'
  ```
  This maps **host port `8040`** to **container port `8030`**, but the app inside the container is actually using port `8080`.

### **Solution**
To resolve the port conflict, you need to map a host port to the correct container port (`8080`) that **paperless-gpt** is using.

1. **Update the Port Mapping:**
   Modify your `docker-compose.yaml` to map **host port `8040`** to **container port `8080`**:
   ```yaml
   ports:
     - '8040:8080'  # HOST_PORT:CONTAINER_PORT
   ```

2. **Revised `docker-compose.yaml`:**
   Here’s the updated configuration for your **paperless-gpt** service:
   ```yaml
   paperless-gpt:
     image: icereed/paperless-gpt:latest
     environment:
       PAPERLESS_BASE_URL: 'http://192.168.178.35:8010'
       PAPERLESS_API_TOKEN: 'TOKENHERE'
       GIN_MODE: release
       LLM_PROVIDER: 'openai' # or 'ollama'
       LLM_MODEL: 'gpt-4o'     # or 'llama2'
       OPENAI_API_KEY: 'TOKENHERE' # Required if using OpenAI
       LLM_LANGUAGE: 'German' # Optional, default is 'English'
       OLLAMA_HOST: 'http://host.docker.internal:11434' # If using Ollama
     volumes:
       - ./prompts:/app/prompts
     ports:
       - '8040:8080'  # Updated port mapping
     depends_on:
       - webserver
   ```

3. **Apply the Changes:**
   Restart your Docker Compose services to apply the new configuration:
   ```bash
   docker-compose up -d
   ```

4. **Access the Service:**
   After restarting, you should be able to access **paperless-gpt** via `http://<your-host-ip>:8040`.

### **Quick Verification**
- **Check Port Mapping:**
  Run `docker ps` to ensure the ports are correctly mapped:
  ```bash
  docker ps
  ```
  Look for something like:
  ```
  0.0.0.0:8040->8080/tcp
  ```

- **Ensure Port Availability:**
  Make sure that **host port `8040`** isn’t being used by another service.

I hope this helps! Let me know if you need any more assistance or if something doesn’t work as expected.

Best regards,  
Icereed
