### ISSUE TITLE
Custom Prompt Templates not used

### ISSUE THREAD

**Issue by stepanov1975** [icereed/paperless-gpt#31]
So, as was reported, templates were not copied to the prompts volume. I copied them manually from /root/prompts to /app/prompts
After I changed them and restarted the container I can see from logs that are still not used.
Relevant part of docker-compose file
```
paperless-gpt:
    image: icereed/paperless-gpt:latest
    container_name: paperless-gpt
    security_opt:
      - no-new-privileges:true
    environment:
      PAPERLESS_BASE_URL: 'http://webserver:8000'
      PAPERLESS_API_TOKEN: '***'
      LLM_PROVIDER: 'openai' # or 'ollama'
      LLM_MODEL: 'gpt-4o'     # or 'llama2'
      OPENAI_API_KEY: '***' # Required if using OpenAI
      LLM_LANGUAGE: 'Hebrew' # Optional, default is 'English'
    volumes:
      - /docker_installs/paperless-ngx/prompts:/app/prompts # Mount the prompts directory
    ports:
      - '8080:8080'
    depends_on:
      webserver:
        condition: service_healthy
```
Files inside prompts directory
![image](https://github.com/user-attachments/assets/54daf83b-dd17-49fa-b990-afc6e722b394)
