### ISSUE TITLE
Use OCR for any everything

### ISSUE THREAD

**Issue by Snify89** [icereed/paperless-gpt#395]
It would be useful to have the OCR do more "work" such as "guessing/extracting" the correspondents, date(s), receiver (as custom field), etc.
Even tagging can change the way we use paperless-ngx cause we'd have "optical" tagging features such as (black/white document, has stains, has logos, and so on...)
This would open up a whole new level since visual models are smart enough already to know the content and layout, symbols etc. at once.
Page settings with different prompts can also be helpful/useful (e.g. extract correspondent only from page 1-3 or so).

**Comment by icereed** [comment]
Actually, you just hit the core of my new idea: I wanna introduce a very flexible, LLM pipeline, workflow definition via YAML.

For your example, it could look like this:

```yaml
- id: enhanced_ocr_with_metadata
  triggers:
    - tag: Rechnung-OCR
    - mime_type: application/pdf
  conditions:
    - prompt: |
        Is this a document worth enhancing with LLM-based OCR?
        Answer true or false.
      expect: true
    - script: |
        return metadata.page_count <= 5
  sequence:
    - service: ocr.llm
      model: openai:gpt-4o
      extract:
        content: true
        fields:
          - title
          - tags
          - correspondent
          - custom_fields:
              invoice_total: |
                What is the total amount of the invoice?
              iban: |
                What IBAN is mentioned on this invoice?
          - meta:
              grayscale: |
                Is this document a grayscale copy? Answer yes or no.
              quality_score: |
                How would you rate the scan quality from 0 to 10?
```

I’m currently working on the spec of the LLM workflow definition. I will create a new discussion to discuss the design.
