### ISSUE TITLE
OCR processing fails with "image: unknown format" error using latest paperless-gpt version (mode: whole_pdf, OpenAI GPT-4.1)

### ISSUE THREAD

**Issue by BlackJoker90** [icereed/paperless-gpt#418]
With the latest paperless-gpt (Docker image: icereed/paperless-gpt:latest), OCR fails for specific documents when using the LLM OCR provider (OpenAI GPT-4.1).

In `whole_pdf` mode:
OCR fails with

Failed to decode image" error="image: unknown format"

This aborts OCR and background tagging for the document. The issue is reproducible with the same files.

In `pdf` mode:
OCR fails with

OCR processing failed: error downloading document PDFs for document 1693: expected split PDF not found: /tmp/paperless-gpt/document-1693-pdf/original_001.pdf

**This blocks OCR for those files entirely.**

```
image: icereed/paperless-gpt:latest
environment:
  PAPERLESS_BASE_URL: 'XXX'
  PAPERLESS_API_TOKEN: 'XXX'
  LLM_PROVIDER: 'openai'
  LLM_MODEL: 'gpt-4.1'
  OPENAI_API_KEY: 'XXX'
  LLM_LANGUAGE: 'German'
  VISION_LLM_PROVIDER: 'openai'
  VISION_LLM_MODEL: 'gpt-4.1'
  LOG_LEVEL: 'info'
  AUTO_OCR_TAG: 'paperless-gpt-ocr-auto'
  OCR_LIMIT_PAGES: '0'
  OCR_PROCESS_MODE: 'whole_pdf'   # or 'pdf'
  PDF_SKIP_EXISTING_OCR: 'true'
  AUTO_GENERATE_CORRESPONDENTS: 'true'
  AUTO_GENERATE_TAGS: 'false'
```
