### ISSUE TITLE
Document loading takes excessively long and no documents are found

### ISSUE THREAD

**Issue by BlackJoker90** [icereed/paperless-gpt#43]
TheThere is a significant performance issue when loading documents: the process takes an unusually long time, and afterward, no documents are found. To test the system, I tagged several documents with "paperless-gpt," but they still do not appear.

I have used the API token from the main Paperless user, and the Paperless NGX instance is installed on port `8777:8000`. Also I get the error message "Failed to reload documents"

**Log Output from Paperless-GPT:**

```
[GIN] 2024/11/11 - 00:11:45 | 500 | 30.007605697s | 192.168.208.1 | GET "/api/documents"

2024/11/11 00:11:45 Error fetching documents: Get "http://xxx:8000/api/documents/?query=tag:paperless-gpt": dial tcp xxx:8000: i/o timeout
```

The system is installed in Portainer using the following docker-compose file:

```
services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    # ... (your existing paperless-ngx configuration)

  paperless-gpt:
    image: icereed/paperless-gpt:latest
    environment:
      PAPERLESS_BASE_URL: 'http://xxx:8000'
      PAPERLESS_API_TOKEN: 'xxx'
      LLM_PROVIDER: 'openai' # or 'ollama'
      LLM_MODEL: 'gpt-4o'     # or 'llama2'
      OPENAI_API_KEY: 'xxx# Required if using OpenAI
      LLM_LANGUAGE: 'German' # Optional, default is 'English'
      VISION_LLM_PROVIDER: 'ollama' # Optional, for OCR
      VISION_LLM_MODEL: 'minicpm-v' # Optional, for OCR
      LOG_LEVEL: 'info' # Optional or 'debug', 'warn', 'error'
    volumes:
      - /volume1/docker/paperless-gpt/prompts:/app/prompts # Mount the prompts directory
    ports:
      - '8080:8080'
    depends_on:
      - paperless-ngx
```
