### ISSUE TITLE
Cannot Use Gemini as Vision LLM Provider

### ISSUE THREAD

**Issue by BlackJoker90** [icereed/paperless-gpt#446]
Description:

With the following docker-compose configuration, I am unable to use Gemini as the Vision/OCR LLM provider:

```
  paperless-gpt:
    image: icereed/paperless-gpt:latest
    environment:
      PAPERLESS_BASE_URL: 'https://paperless.datafortress.myds.me'
      PAPERLESS_API_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      LLM_PROVIDER: 'googleai'
      LLM_MODEL: 'gemini-2.5-pro-preview-05-06'
      GOOGLEAI_API_KEY: 'xxx'
      OPENAI_API_KEY: 'xxx'
      LLM_LANGUAGE: 'German'
      VISION_LLM_PROVIDER: 'openai'        # Must be either openai or ollama
      VISION_LLM_MODEL: 'gpt-4o'
      LOG_LEVEL: 'info'
      AUTO_OCR_TAG: 'paperless-gpt-ocr-auto'
      OCR_LIMIT_PAGES: '0'
      OCR_PROCESS_MODE: 'pdf'
      PDF_SKIP_EXISTING_OCR: 'true'
      AUTO_GENERATE_CORRESPONDENTS: 'true'
      AUTO_GENERATE_TAGS: 'false'
```

My goal:
Use Gemini as the Vision LLM for OCR.

The problem:
	•	According to the docs, VISION_LLM_PROVIDER must be either openai or ollama.
	•	If I set VISION_LLM_PROVIDER to googleai or try to use a Gemini model, nothing works—Paperless-GPT either fails to start or doesn’t use GoogleAI/Gemini at all.
	•	The documentation is extremely vague here. Which combinations are actually supported? Is it possible to use Gemini (via GoogleAI) as the Vision provider? If not: why? If yes: how?

My impression: Either Gemini is not supported as a Vision/OCR provider at all, or the necessary config is simply not described in the docs (https://github.com/icereed/paperless-gpt).

Expected behavior:
Gemini should work as a Vision LLM provider, or it should be clearly documented why it is not supported and which options are.

Questions:
	•	Which LLM/Vision provider combinations are actually supported?
	•	Is Gemini supported for Vision/OCR at all?
	•	If not: is there any ETA for support, or a workaround?

Thanks for clarifying! Right now, the documentation on this topic is as clear as mud.
