### ISSUE TITLE
[FR] Persistent history

### ISSUE THREAD

**Issue by vistalba** [icereed/paperless-gpt#479]
I use paperless-gpt as a docker container within my k8s cluster. After a restart of the pod, the history is always empty. Because of that I loose the history of all previously processed documents and changes.

My mounted paths looks like this:

```
        volumeMounts:
        - name: paperless-gpt-prompts
          mountPath: "/app/prompts"
        - name: paperless-gpt-hocr
          mountPath: "/app/hocr"
        - name: paperless-gpt-pdf
          mountPath: "/app/pdf"
```

Is there a way to make it persistent already?
