### ISSUE TITLE
Web App -> Empty Response

### ISSUE THREAD

**Issue by tttuntcloud** [icereed/paperless-gpt#69]
Hi,
it’s me again.
Since the update for the additional dependencies for title/tag generation, I can no longer access the web interface.
My browser always reports an "Empty Response" error.
I completely deleted the container and re-pulled the image, even changed the port – but it’s still not working :-(.

There’s nothing unusual in the log file, and I’ve already switched to debug mode. However, there are no new messages beyond what was already logged before.
I’ve set the WebUI path (and tested both options mentioned in the README), but unfortunately, the web interface still remains inaccessible.

Log:
2025/01/06 20:42:51 | stderr | time="2025-01-06T19:42:51Z" level=debug msg="No documents with tag paperless-gpt-auto found"
2025/01/06 20:42:40 | stderr | time="2025-01-06T19:42:40Z" level=debug msg="No documents with tag paperless-gpt-auto found"
2025/01/06 20:42:29 | stderr | time="2025-01-06T19:42:29Z" level=debug msg="No documents with tag paperless-gpt-auto found"
2025/01/06 20:42:28 | stdout | [GIN-debug] Listening and serving HTTP on 127.0.0.1:8080
2025/01/06 20:42:28 | stdout | Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
2025/01/06 20:42:28 | stdout | [GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
2025/01/06 20:42:28 | stdout | time="2025-01-06T19:42:28Z" level=info msg="Worker 0 started"
2025/01/06 20:42:28 | stdout | [GIN-debug] HEAD   /vite.svg                 --> main.main.(*RouterGroup).StaticFile.func7 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /vite.svg                 --> main.main.(*RouterGroup).StaticFile.func7 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] HEAD   /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/paperless-url        --> main.main.func4 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] POST   /api/undo-modification/:id --> main.(*App).undoModificationHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/modifications        --> main.(*App).getModificationHistoryHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/experimental/ocr     --> main.main.func3 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/jobs/ocr             --> main.(*App).getAllJobsHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/jobs/ocr/:job_id     --> main.(*App).getJobStatusHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] POST   /api/documents/:id/ocr    --> main.(*App).submitOCRJobHandler-fm (3 handlers)
2025/01/06 20:42:28 | stderr | time="2025-01-06T19:42:28Z" level=info msg="Server started on interface 127.0.0.1:8080"
2025/01/06 20:42:28 | stdout | [GIN-debug] POST   /api/prompts              --> main.updatePromptsHandler (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/prompts              --> main.getPromptsHandler (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/tags                 --> main.(*App).getAllTagsHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/filter-tag           --> main.main.func2 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] PATCH  /api/update-documents     --> main.(*App).updateDocumentsHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] POST   /api/generate-suggestions --> main.(*App).generateSuggestionsHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/documents/:id        --> main.main.(*App).getDocumentHandler.func6 (3 handlers)
2025/01/06 20:42:28 | stdout | [GIN-debug] GET    /api/documents            --> main.(*App).documentsHandler-fm (3 handlers)
2025/01/06 20:42:28 | stdout |  
2025/01/06 20:42:28 | stdout | - using code: gin.SetMode(gin.ReleaseMode)
2025/01/06 20:42:28 | stdout | - using env: export GIN_MODE=release
2025/01/06 20:42:28 | stdout | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
2025/01/06 20:42:28 | stdout |  
2025/01/06 20:42:28 | stdout | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

**Comment by icereed** [comment]
Hi, I just repulled the image on all my devices and it still works for me with the default settings for the web ui path and the interface. Can you post your settings (secret stuff redacted ;) )?

**Comment by gima84** [comment]
Hi, I had the same issue. Seems to be related to parameter WEBUI_PATH. With "/usr/share/paperless-gpt/webui" it was not working. I have changed it to "./web-app/dist" and now the webpage is available.

**Comment by icereed** [comment]
Okay, I see the Problem. The doctor compose example included a problematic setting of the web Ui path. I removed it in #85. With docker you are not supposed to overwrite this environment variable as it already matches the default. 

Thank you for bringing this up.

**Comment by tttuntcloud** [comment]
Sorry - but still does not work :-(.

```
version: '3.7'
services:
  paperless-gpt:
    image: icereed/paperless-gpt:latest
    environment:
      PAPERLESS_BASE_URL: 'http://192.#'
      PAPERLESS_API_TOKEN: '#'
      PAPERLESS_PUBLIC_URL: 'http://paperless.#.de' # Optional, your public link to access Paperless
      MANUAL_TAG: 'paperless-gpt' # Optional, default is 'paperless-gpt'
      AUTO_TAG: 'paperless-gpt-auto' # Optional, default is 'paperless-gpt-auto'
      LLM_PROVIDER: 'openai' # or 'ollama'
      LLM_MODEL: 'gpt-4o-mini'     # or 'llama2'
      OPENAI_API_KEY: '#' # Required if using OpenAI
      LLM_LANGUAGE: 'German' # Optional, default is 'English'
      OLLAMA_HOST: 'http://host.docker.internal:11434' # If using Ollama
      VISION_LLM_PROVIDER: 'openai' # Optional (for OCR) - ollama or openai
      VISION_LLM_MODEL: 'gpt-4o' # Optional (for OCR) - minicpm-v, for example for ollama, gpt-4o for openai
      AUTO_OCR_TAG: 'paperless-gpt-ocr-auto' # Optional, default is 'paperless-gpt-ocr-auto'
      LOG_LEVEL: 'info' # Optional or 'debug', 'warn', 'error'
      LISTEN_INTERFACE: '127.0.0.1:8080' # Optional, default is ':8080'
      AUTO_GENERATE_TITLE: 'true'
      AUTO_GENERATE_TAGS: 'false'
    volumes:
      - ./prompts:/app/prompts # Mount the prompts directory
    ports:
      - '8089:8080'
```

Thats my YAML.

Yes – I know the Paperless-NGX service is missing; Paperless is already running in a separate container, and with the last version, it didn’t seem to be relevant (at least it worked without it, and the UI should still be accessible, right?).

Two things I’ve noticed in den Logs: In the configuration, the log level is set to "info" again, but I’m still seeing debug output in the logs. Was it like that before as well?
the second: the log also states that the service started on 127.0.0.1:8000. Did I misconfigure something here or is it correct, because Docker routes it to the right address? I would expect to access it via 192.xxxxxx:8089...

**2025/01/07 12:04:29 | stderr | time="2025-01-07T11:04:29Z" level=info msg="Server started on interface 127.0.0.1:8080"**
2025/01/07 12:04:29 | stdout | time="2025-01-07T11:04:29Z" level=info msg="Worker 0 started"
2025/01/07 12:04:29 | stdout | [GIN-debug] Listening and serving HTTP on 127.0.0.1:8080
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.

Many Thanks for your help :).
